version: '3.8'

services:
  postgres:
    container_name: odoo-postgres
    image: postgres:14.1-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  odoo:
    container_name: odoo
    image: odoo:18.1
    environment:
      HOST: postgres
      USER: odoo
      PASSWORD: secret
      # Added for testing
      TEST_ENABLE: ${TEST_ENABLE:-False}
      LOG_LEVEL: ${LOG_LEVEL:-info}
      WITHOUT_DEMO: ${WITHOUT_DEMO:-False}
    depends_on:
      - postgres
    ports:
      - 8069:8069
    volumes:
      - ./config:/etc/odoo
      - ./modules:/mnt/extra-addons
      - data:/var/lib/odoo
    restart: always
    links:
      - postgres
    # This command is used when TEST_ENABLE is True
    command: >
      ${ODOO_COMMAND:-}
      
volumes:
  postgres-data:
  data:
