version: '3.8'
services:
  web:
    image: odoo:18.1
    depends_on:
      - db
    volumes:
      - ./config:/etc/odoo
      - ./modules_to_test:/mnt/extra-addons/modules_to_test
      - ./dependencies:/mnt/extra-addons/dependencies
      - ./test_reports:/var/log/odoo
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
      # Testing specific variables
      - TEST_ENABLE=True
      - LOG_LEVEL=test
      - MODULES_TO_TEST=${MODULES_TO_TEST:-all}
      - WITHOUT_DEMO=False
    command: >
      -- --test-enable --stop-after-init --log-level=test
         --test-tags=${TEST_TAGS:-/}
         -d test_db
         -i ${MODULES_TO_TEST}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8069/web/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=test_db
    volumes:
      - db-data:/var/lib/postgresql/data
    tmpfs:
      - /var/lib/postgresql/data

volumes:
  db-data:
    driver: local
