version: '3.8'

services:
  postgres:
    container_name: odoo-postgres
    image: postgres:14.1-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}  # Render provides this value
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  odoo:
    container_name: odoo
    image: odoo:18
    environment:
      HOST: postgres
      USER: odoo
      PASSWORD: ${POSTGRES_PASSWORD}
      # Additional environment variables for testing and logging
      TEST_ENABLE: ${TEST_ENABLE:-False}
      LOG_LEVEL: ${LOG_LEVEL:-info}
      WITHOUT_DEMO: ${WITHOUT_DEMO:-False}
    depends_on:
      - postgres
    ports:
      - 8069:8069
    volumes:
      - ./config:/etc/odoo
      - ./modules:/mnt/extra-addons
      - data:/var/lib/odoo
    restart: always
    # Override the command to listen on the Render-assigned PORT (defaulting to 8069 locally)
    command: ${ODOO_COMMAND:-odoo --http-port ${PORT:-8069}}

volumes:
  postgres-data:
  data:
