services:
  - type: web
    name: odoo-app
    env: docker
    dockerfilePath: ./Dockerfile
    plan: standard
    healthCheckPath: /web
    envVars:
      - key: PGHOST
        value: dpg-cv3djqin91rc739ernr0-a
      - key: PGPORT
        value: "5432"
      - key: PGDATABASE
        value: mytestdb_aa42
      - key: PGUSER
        value: mytestdb_aa42_user
      - key: PGPASSWORD
        value: "S3D3y1nOjq8PqnnfbQDyTSuvPTrPeZjm"
