services:
  - type: web
    name: odoo-app
    env: docker
    dockerfilePath: ./Dockerfile
    plan: standard
    healthCheckPath: /web
    envVars:
      - key: POSTGRES_PASSWORD
        generateValue: true
      - key: POSTGRES_USER
        value: odoo
